### ISSUE TITLE
[LEAGUE LOADER]: Yahoo league loader fails when it incorrectly detects 2 championship matchups

### ISSUE THREAD

**Issue by brian-dev8** [joeyagreco/leeger#29]
### League Loader

Yahoo

### Summary

Yahoo league loader fails when it incorrectly detects 2 championship matchups.  One of the matchups is a consolation.

### Error Logs

`Error
Traceback (most recent call last):
  File "C:\D\windows\git\leeger\test\test_league_loader\test_YahooLeagueLoader.py", line 47, in test_league
    leagueToExcel(league, "C:/D/windows/git/leeger/dsbLeagueStats.xlsx")
  File "C:\D\windows\git\leeger\leeger\util\excel.py", line 24, in leagueToExcel
    yearToExcel(year, filePath, **kwargs)
  File "C:\D\windows\git\leeger\leeger\util\excel.py", line 154, in yearToExcel
    statsWithTitles = yearStatSheet(year, **kwargs).preferredOrderWithTitle()
  File "C:\D\windows\git\leeger\leeger\util\stat_sheet.py", line 92, in yearStatSheet
    wins = GameOutcomeYearCalculator.getWins(year, **kwargs)
  File "C:\D\windows\git\leeger\leeger\decorator\validators.py", line 65, in wrapFunction
    yearValidation.runAllChecks(year)
  File "C:\D\windows\git\leeger\leeger\validate\yearValidation.py", line 20, in runAllChecks
    checkAllWeeks(year)
  File "C:\D\windows\git\leeger\leeger\validate\yearValidation.py", line 40, in checkAllWeeks
    weekValidation.runAllChecks(week)
  File "C:\D\windows\git\leeger\leeger\validate\weekValidation.py", line 16, in runAllChecks
    checkWeekDoesNotHaveMoreThanOneChampionshipMatchup(week)
  File "C:\D\windows\git\leeger\leeger\validate\weekValidation.py", line 83, in checkWeekDoesNotHaveMoreThanOneChampionshipMatchup
    raise InvalidWeekFormatException(
leeger.exception.InvalidWeekFormatException.InvalidWeekFormatException: Week 16 has 2 championship matchups. Maximum is 1.`

**Comment by joeyagreco** [comment]
This has been fixed in [version 1.3.1](https://github.com/joeyagreco/leeger/releases/tag/v1.3.1).
