### ISSUE TITLE
[LEAGUE LOADER]: Fails on TypeError

### ISSUE THREAD

**Issue by willmythical** [joeyagreco/leeger#34]
### League Loader

Yahoo

### Summary

This is probably user error and not the forum for support, but I wasn't sure how else to reach out for help. League Loader fails with `TypeError: dataclass() got an unexpected keyword argument 'kw_only'` 

### League Info

Yahoo league ID# 14981 - it may be private.

### Error Logs

```
Traceback (most recent call last):
  File "/home/wcarter/scratch/fantasy-stats/stats.py", line 1, in <module>
    from leeger.league_loader import YahooLeagueLoader
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12/lib/python3.9/site-packages/leeger/league_loader/__init__.py", line 1, in <module>
    from .ESPNLeagueLoader import ESPNLeagueLoader
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12/lib/python3.9/site-packages/leeger/league_loader/ESPNLeagueLoader.py", line 6, in <module>
    from leeger.league_loader.LeagueLoader import LeagueLoader
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12/lib/python3.9/site-packages/leeger/league_loader/LeagueLoader.py", line 5, in <module>
    from leeger.model.league.League import League
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12/lib/python3.9/site-packages/leeger/model/league/__init__.py", line 1, in <module>
    from .League import League
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12/lib/python3.9/site-packages/leeger/model/league/League.py", line 6, in <module>
    from leeger.model.league.Owner import Owner
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12/lib/python3.9/site-packages/leeger/model/league/Owner.py", line 9, in <module>
    @dataclass(kw_only=False, eq=False)
TypeError: dataclass() got an unexpected keyword argument 'kw_only'
```

**Comment by joeyagreco** [comment]
This is due to being on a Python version that is less than 3.10. Make sure you're running on Python 3.10.
