### ISSUE TITLE
[LEAGUE LOADER]: AttributeError: 'Matchup' object has no attribute 'winner_team_key'

### ISSUE THREAD

**Issue by willmythical** [joeyagreco/leeger#40]
### League Loader

Yahoo

### Summary

Yahoo league loader errors out when an actual tie has occurred on a Yahoo league season.

### League Info

League ID: 137588
Year: 2018

### Error Logs

```
Traceback (most recent call last):
  File "/Users/whcarter3/scratch/ETFLstats/stats.py", line 37, in <module>
    league: League = yahooLeagueLoader.loadLeague()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 73, in loadLeague
    return self.__buildLeague(yahooLeagues)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 81, in __buildLeague
    years.append(self.__buildYear(yahooLeague))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 87, in __buildYear
    weeks = self.__buildWeeks(yahooLeague)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 106, in __buildWeeks
    teamAHasTiebreaker = yahooMatchup.winner_team_key == yahooTeamA.team_key and yahooMatchup.is_tied == 0
AttributeError: 'Matchup' object has no attribute 'winner_team_key'
```

**Comment by joeyagreco** [comment]
@willmythical 

Just put out a fix for this in [version 1.2.0](https://github.com/joeyagreco/leeger/releases/tag/v1.2.0)

If you run `pip install --upgrade leeger` and then run the script again this bug _should_ be resolved.

Please let me know if that works so I can close this issue.

**Comment by willmythical** [comment]
Seems to return same error after upgrading to `1.2.0`. Also noting I have to include the code from [PR 30 ](https://github.com/joeyagreco/leeger/pull/30) for the Yahoo league loader to work for me.

Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/whcarter3/scratch/ETFLstats/stats.py", line 37, in <module>
    league: League = yahooLeagueLoader.loadLeague()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 73, in loadLeague
    return self.__buildLeague(yahooLeagues)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 81, in __buildLeague
    years.append(self.__buildYear(yahooLeague))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 87, in __buildYear
    weeks = self.__buildWeeks(yahooLeague)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/leeger/league_loader/YahooLeagueLoader.py", line 106, in __buildWeeks
    teamAHasTiebreaker = yahooMatchup.winner_team_key == yahooTeamA.team_key and yahooMatchup.is_tied == 0
AttributeError: 'Matchup' object has no attribute 'winner_team_key'
```

**Comment by joeyagreco** [comment]
@willmythical 

Looks like you're not running the code in 1.2.0 somehow.. the error you're getting is on line 106 but the line of code the error is stating is how the code was in 1.1.1, not 1.2.0.

This might be because of how you're merging the code from PR 30 (which does NOT have the latest 1.2.0 changes).

Would you be willing to share your clientId and clientSecret with me via email so I can troubleshoot this for your league locally?

If you're not comfortable with that, we can perhaps set up a video call and you can share your screen to help debug this issue.

**Comment by joeyagreco** [comment]
This issue was likely fixed in [version 1.3.2](https://github.com/joeyagreco/leeger/releases/tag/v1.3.2).

Please update to that version and test / report back here if that fixed your issue.
